### ISSUE TITLE
Mouse events work incorrectly in fullscreen on Chrome

### ISSUE THREAD

**Issue by mourner** [brunob/leaflet.fullscreen#1]
In full screen on latest Chrome, mouse-wheel-zoom and double-click-zoom work incorrectly. This is related to the way they get mouse pointer's position relative to the container. Localized the problem: try to run the following line in console in fullscreen:

```
L.DomUtil.getViewportOffset(map._container).toString();
```

So somehow this method needs to be fixed to adjust for fullscreen mode.

**Comment by brunob** [comment]
Fixed in latest chrome as in Leaflet/Leaflet.fullscreen#1
