### ISSUE TITLE
Upgrade to screenfull 6.0.x

### ISSUE THREAD

**Issue by pauloxnet** [brunob/leaflet.fullscreen#109]
A new version of `screenfull` has been released:
https://github.com/sindresorhus/screenfull

**Comment by BePo65** [comment]
screenfull v6 is a esm only version of screenfull. As the author states in the [readme](https://github.com/sindresorhus/screenfull#screenfull)

>If you cannot use ESM or need to support older browsers without using transpilation, use version 5.2.0.

As leaflet itself is yet far away from esm (see [releases](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.0)) that is also true for its plugins and for all packages used by this plugins (e.g. screenfull in leaflet.fullscreen).

=> Leaflet.fullscreen cannot use dependencies that are esm only (like screenfull v6).
