### ISSUE TITLE
Not working properly on iOS when using an iframe

### ISSUE THREAD

**Issue by leandroprz** [brunob/leaflet.fullscreen#110]
Hi,

I tested the plugin using a map inside an iframe and I noticed that when accessing the page from an iPhone using Safari, it doesn't go into full screen mode.

The page with the iframe: https://dev.leandroperez.art/mapa-timelapse/teste.html
The page with the map itself: https://dev.leandroperez.art/mapa-timelapse/teste.php

The iframe HTML in `teste.html`:

`<iframe style="border:0;" src="https://dev.leandroperez.art/mapa-timelapse/teste.php" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" width="100%" height="425"></iframe>`

**Comment by brunob** [comment]
It seems a limitation of safari on ios ref https://caniuse.com/fullscreen & https://forum.defold.com/t/html-fullscreen-under-iphone-solved/69141/4

**Comment by leandroprz** [comment]
I assume there's no workaround for this limitation?

**Comment by brunob** [comment]
i think so...
