### ISSUE TITLE
Button state incorrect when multiple maps on a page

### ISSUE THREAD

**Issue by skirridsystems** [brunob/leaflet.fullscreen#117]
If there are multiple maps on a page, e.g. showing different walking routes in an area, if you enter and then exit fullscreen on one map, the fullscreen button on all the other maps then shows the exit fullscreen icon and text, even though they are clearly not fullscreened.

This only affects buttons which have not yet been clicked. If I then fullscreen/exit on a different map, the first map to be fullscreened shows the correct icon state.

**Comment by brunob** [comment]
Nice catch !

**Comment by brunob** [comment]
'k the bug come from `_handleFullscreenChange()` which is fired on `fullscreenchange` event for every map on the page leading to the bug :\
