### ISSUE TITLE
Icon is not visible in stencil

### ISSUE THREAD

**Issue by EugenTK10** [brunob/leaflet.fullscreen#128]
Hello, 

On my leaflet map, the button is showing up but the actual icon is not. I am using stencil.js and leaflet.js. 
These are the relevant used version and packages:
   "@stencil/core": "^4.7.0",
    "@types/leaflet": "^1.9.12",
    "@typesleaflet.fullscreen/": "^3.0.2",
    "leaflet.fullscreen": "^3.0.2"

I import it as:
import "leaflet.fullscreen";
and use it as
map1 = L.map(container, {
      fullscreenControl: true,
      fullscreenControlOptions: {
        position: "topleft",
        forceSeparateButton: true,
      },
What should I do to make the icon appear?

**Comment by brunob** [comment]
We can't help you without any url showing the problem online. Inspect your page with dev tools to see if a personal CSS is overriding the fullscreen icon styles.

**Comment by EugenTK10** [comment]
I needed to make the svg icon visible for stencil in the www folder, which required overridding the css with something like

.fullscreen-icon {
	background-image: url('build/icon-fullscreen.svg');
}

and it worked
