### ISSUE TITLE
Whitelist divs?

### ISSUE THREAD

**Issue by brorfred** [brunob/leaflet.fullscreen#41]
Is there a way to whitelist a div that overlays information when switching to full screen? I have an overlay with detailed information that disappears in fullscreen mode: http://ecoa.cruiseplan.org

**Comment by Eschon** [comment]
When entering fullscreen Browsers add a very high z-index (the maximum I believe) to the object that is displayed in fullscreen. Here an example from Safari:

![screen shot 2015-06-08 at 11 05 49](https://cloud.githubusercontent.com/assets/11647830/8031449/9780ba06-0dce-11e5-8687-aeb42b315a30.png)

If you add that z-index value to the css for your div it should be displayed on top as long as it comes after the map in the DOM tree.

**Comment by brunob** [comment]
Two options here, specify the z-index of your overlay as said bu @Eschon or simply put your div in a map pane :)
