### ISSUE TITLE
Fullscreen Chrome Mobile

### ISSUE THREAD

**Issue by SilentT-FR** [brunob/leaflet.fullscreen#42]
When i activate fulscreen
the screen was cut in twice
the buble disapear but the screen remains like this
Work in Firefox mobile and Desktop Plateform
the screen is normal when no fullscreen

![screenshot_2015-06-13-14-26-33](https://cloud.githubusercontent.com/assets/4253130/8144323/d8f94f58-11d8-11e5-9001-a0b668be884d.png)

**Comment by brunob** [comment]
Does this works better if you apply https://github.com/brunob/leaflet.fullscreen/blob/master/Control.FullScreen.css#L3 to your map ?

**Comment by SilentT-FR** [comment]
Same problem and ive lost the icon
the initial file
.leaflet-control-zoom-fullscreen { background-image: url(icon-fullscreen.png); }
.leaflet-retina .leaflet-control-zoom-fullscreen { background-image: url(icon-fullscreen-2x.png); background-size: 26px 26px; }
.leaflet-container:-webkit-full-screen { width: 100% !important; height: 100% !important; z-index: 99999; }
.leaflet-pseudo-fullscreen { position: fixed !important; width: 100% !important; height: 100% !important; top: 0px !important; left: 0px !important; z-index: 99999; }

**Comment by SilentT-FR** [comment]
i have test with your demo website and it works perfectly
so i search why with my website sucks

**Comment by SilentT-FR** [comment]
Sorry for the noise

i don't use the recommendation of leaflet 

html, body, #map {
    height: 100%;
}

i have use inline witdth 100% position relative on the map div 
html and body  get forgotten ^^

**Comment by SilentT-FR** [comment]
Sorry for the noise

i don't use the recommendation of leaflet 

html, body, #map {
    height: 100%;
}

i have use inline witdth 100% position relative on the map div 
html and body  get forgotten ^^
