### ISSUE TITLE
Nice work... I also suggest to...

### ISSUE THREAD

**Issue by wocmultimedia** [brunob/leaflet.fullscreen#44]
Hi Bruno,

Nice work. Simple to use and works fine on Chrome. I'm not a developer but following your instructions I got this result http://www.wocmultimedia.biz/en/cilavegna-and-italy/

I don't know if it's simple to achieve but I suggest the options of having double title for going to Full Screen and exit from Full Screen, so far you have only one option to set using "title:...."
Thanks
Angelo

**Comment by brunob** [comment]
Here you go, you can now use titleCancel option for that ;)

**Comment by wocmultimedia** [comment]
thanks. Have a good day Bruno.

Angelo
