### ISSUE TITLE
Same height on Chrome and black on the rest of the screen

### ISSUE THREAD

**Issue by rastapopougros** [brunob/leaflet.fullscreen#48]
Coucou :)

On Chrome (Chromium, Ubuntu), Fullscreen keeps the same height as it was on the page, and black on the rest of the screen.

Ex : https://www.agri-lyonnaise.top/carte-de-zones-titre-a-trouver

Maybe a conflict because the map is on absolute position ?

But it works on other browsers. Broken only on Chrome.

(And even, it has freeze all my screen when I wanted to leave fullscreen, but for that it must be a Chromium bug…)

**Comment by brunob** [comment]
Comme on en parlait sur IRC, le bug vient du fait que tu appliques une position absolute à ta carte dans les css de ton projet. On applique les règles css mini pour prendre en charge le plein écran dans la lib, mais on ne peut pas présumer de "la force" des sélecteurs utilisés par les gens sur leur site...

**Comment by rastapopougros** [comment]
Sauf que le bug n'apparait absoluement que dans Chrome. Ça marche partout sinon. Donc ma carte en absolue *et* fullscreen marche bien dans la plupart des navs, ya un truc spécifique à Chrome…

**Comment by brunob** [comment]
@rastapopougros le bug est-il toujours d'actualité ? (j'ai voulu vérifier mais ton lien est en 404)

**Comment by martinschilliger** [comment]
I had max-width and max-height set, is it the same for you?

**Comment by BePo65** [comment]
I can see the problem if I use the link [https://www.agri-lyonnaise.top/carte-des-enjeux-et-mesures](https://www.agri-lyonnaise.top/carte-des-enjeux-et-mesures).

Perhaps @rastapopougros could create a demo for the problem only (without all the details of the webpage) on [codepen](https://codepen.io/pen/) or one of the other playgrounds, just to make it easier to analyze it.

**Comment by brunob** [comment]
I think it should be resolved with v2, closig for now and let's see if @rastapopougros still has the bug when i'll introduce v2 in https://git.spip.net/spip-contrib-extensions/gis
