### ISSUE TITLE
isFullScreen() checks wrong property when no prefix used

### ISSUE THREAD

**Issue by prettyv** [brunob/leaflet.fullscreen#55]
Under current versions of Firefox Developer Edition document.exitFullscreen is defined, so the unprefixed case is hit in fullscreenApi.isFullScreen().

The fullscreen property is called document.fullscreen (all lowercase) as specified [here](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API), while currently document.fullScreen is used (https://github.com/brunob/leaflet.fullscreen/blob/master/Control.FullScreen.js#L158), which breaks the check.

**Comment by brunob** [comment]
@prettyv thx for the hint, feel free to provide a pull request.
