### ISSUE TITLE
Would be nice to have classes added to the control when in/out full screen mode.

### ISSUE THREAD

**Issue by sdlime** [brunob/leaflet.fullscreen#57]
Presently the title changes on the buttons between _Full Screen_ and _Exit Full Screen_. It would be nice if classes were also available on the button that reflected current state. I think then it would be easier to change the button styling with pure CSS. --Steve

**Comment by brunob** [comment]
The simplest patch would be to rename `_toggleTitle()` to something like `_toggleButton()` and toggle the class on the button from here. Feel free to provide a pull request if it take ma too long to react ;)

**Comment by sdlime** [comment]
I'll to that, thanks for the feedback... --Steve

**Comment by brunob** [comment]
@sdlime any news about this ?

**Comment by sdlime** [comment]
I haven't spent time with this but I need to. Do you have a timeline in mind or just checking? --Steve

________________________________

**Comment by brunob** [comment]
I was bumping about your pull request ;)

**Comment by brunob** [comment]
@sdlime after all, it seems already achievable by targeting `.leaflet-container:fullscreen .leaflet-control-zoom-fullscreen`, not sure we need a specific class on the button. Any thoughts about it ? Can we close the issue ?

**Comment by sdlime** [comment]
I’ll try it on this end but go ahead and close the issue and we can always re-open as necessary.

**Comment by brunob** [comment]
'k thx for feedback, closing :)
