### ISSUE TITLE
Sidebar plugin disappear when using 

### ISSUE THREAD

**Issue by iquays** [brunob/leaflet.fullscreen#58]
Hi there,
thanks for your useful plugin.

I use your plugin along with sidebar-v2 plugin (https://github.com/Turbo87/sidebar-v2).

When I use this plugin's button to enter the fullscreen, the sidebar disappear.
While, the sidebar remain there if I use F11 key to enter fullscreen.

Please help, thanks.
Syauqi

**Comment by brunob** [comment]
May be related to https://github.com/Turbo87/sidebar-v2/issues/105 but i can't tell you more without a fiddle exposing the bug online. Anyway, i think the bug comes from your local css or from sidebar plugin, so the bug should be on its repo not here...

**Comment by iquays** [comment]
Hi Bruno,

I've managed to solve my problem only by moving `<div>` of the _sidebar_ INSIDE `<div>` of the _map_.

Original (wrong) code:
```
<div id="sidebar">
</div>

<div id="map">
</div>
```
Fixed code:
```
<div id="map">
    <div id="sidebar">
    </div>
</div>

```

Silly me...

Sorry and thanks for your guidance.
