### ISSUE TITLE
Part of the screen get covered

### ISSUE THREAD

**Issue by dave7777** [brunob/leaflet.fullscreen#60]
for some reason in the fullscreen view the upper part of the screen is filled with the black background - I have attachedthe screenshot.....do you think this is a bug?

<a href="http://tinypic.com?ref=4vlcus" target="_blank"><img src="http://i64.tinypic.com/4vlcus.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by brunob** [comment]
Which browser ? Any link to a demo page showing the bug ? etc

**Comment by brunob** [comment]
No news, closing...
