### ISSUE TITLE
some tile do not show in chrome

### ISSUE THREAD

**Issue by dfy167** [brunob/leaflet.fullscreen#61]
some tile do not show in chrome when in this env
F11 to get chrome fullscreen
click control button of this plu . and then some tile do not show. 
just use the demo in this site:http://brunob.github.io/leaflet.fullscreen/

**Comment by brunob** [comment]
> click control button of this plu . and then some tile do not show.

can't understand what you're trying to say here :\

**Comment by dfy167** [comment]
http://brunob.github.io/leaflet.fullscreen/

**Comment by dfy167** [comment]
http://brunob.github.io/leaflet.fullscreen/     chrome latest leaflet 1.3
1. open the demo
2. F11 to use chrome function to get full screen. 
3. now ,to click the botton on the map to get map full screen
4. then ,the map is fullscreen ,but the right side has a lot of blank.

leaflet 1.1 has no this problem .
i fix it by this:
```
setTimeout(function () {
        map.invalidateSize()
      }, 10)
```
and when set 10 to 1,the right side has a lot of blank. after some test,i set it to 10 on my computer

**Comment by brunob** [comment]
Version 1.4.5 should fix this bug ;)
