### ISSUE TITLE
Add support for toggling fullscreen via the API.

### ISSUE THREAD

**Issue by m1dst** [brunob/leaflet.fullscreen#63]
Whilst I see the method for toggling fullscreen, it would be good if it were exposed on the map object.

eg: `map.toggleFullScreen();`

Any chance you could add this support?

It seems something similar has been done on
https://github.com/Leaflet/Leaflet.fullscreen/blob/gh-pages/dist/Leaflet.fullscreen.js but I prefer your plugin.

I'm bodging at the minute by issuing 

`$(".leaflet-control-zoom-fullscreen.fullscreen-icon")[0].click();`

**Comment by dantart** [comment]
L.control.fullscreen().addTo(map).toggleFullScreen()

**Comment by brunob** [comment]
Maybe it's time to switch to another fullscreen API wrapper, i've seen these one : 

https://github.com/rafrex/fscreen
https://github.com/sindresorhus/screenfull.js

**Comment by brunob** [comment]
Patch pushed on #65 @m1dst could you test it ?

**Comment by m1dst** [comment]
Thanks for adding it but based on your advice I switched away.  The patch looks reasonable though.

**Comment by brunob** [comment]
'k, thx for the feedback.
