### ISSUE TITLE
enable Fullscreen API on Safari

### ISSUE THREAD

**Issue by sharess** [brunob/leaflet.fullscreen#64]
I noticed that when i enable Fullscreen API on Safari (iPad), any "operation" (pinch, etc) cause exit Fullscreen mode.
Is there a work around to solve it ?

Thanks
sharess

**Comment by brunob** [comment]
Do you have the same bug with https://github.com/Leaflet/Leaflet.fullscreen/ ?

**Comment by sharess** [comment]
I noticed that the last version of browser Safari deletes option Fullscreen API.

**Comment by sharess** [comment]
Now i am watching this "button" when i enter in fullscreen mode ? Diagonal cross for to close fullscreen mode. As in the picture.
Thanks
![Schermata 2019-04-07 alle 16 18 15](https://user-images.githubusercontent.com/1212374/55684957-5da79e80-5951-11e9-9418-12a34b18c5a4.png)

**Comment by sharess** [comment]
About return to origin question, yes with https://github.com/Leaflet/Leaflet.fullscreen/ is the same effect ....
i think i will have to delete fullscreen function if agent is safari :-(

**Comment by brunob** [comment]
@sharess could you test against 2.0.0 version please ?

**Comment by brunob** [comment]
no feedback, closing, feel free to comment if needed

**Comment by sharess** [comment]
Sorry i've lost the answer, OK better.
