### ISSUE TITLE
Button Accessibility Issue

### ISSUE THREAD

**Issue by sdlime** [brunob/leaflet.fullscreen#66]
Hi: The control throws an accessibility error when using the Wave Accessibility Tool (https://webaim.org). The issue is there's no text associated with the control button link. The fix is easy - add an aria-label attribute to the link so it becomes:

`<a class="leaflet-control-zoom-fullscreen fullscreen-icon" href="#" title="Full Screen" aria-label="Full Screen" style="outline: none;"></a>`

This would match the pattern leaflet uses with it's built in zoom in/out control.

--Steve

**Comment by brunob** [comment]
Fixed in 1.5.1, thx for the hint :)
