### ISSUE TITLE
calling toggleFullScreen() results in error

### ISSUE THREAD

**Issue by Exscotticus** [brunob/leaflet.fullscreen#72]
Great plugin!

I want to start in fullscreen mode. So I tried to programmatically call toggleFullScreen() as follows...

```
var fullscreen = L.control.fullscreen();
fullscreen.addTo(map);
fullscreen.toggleFullScreen();
```

This results in the following error...

```
Control.FullScreen.js:178 Uncaught (in promise) TypeError: fullscreen error
    at Object.fullScreenApi.requestFullScreen (Control.FullScreen.js:178)
    at i.toggleFullScreen (Control.FullScreen.js:78)
    at HTMLDocument.<anonymous> ((index):143)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)

Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
Uncaught (in promise) TypeError: fullscreen error
```

**Comment by brunob** [comment]
as the error mention, you can't "API can only be initiated by a user gesture." cf "The main restriction that the API places on developers is that fullscreen must be triggered in reaction to a click or keypress." https://feross.org/html5-fullscreen-api-attack/
