### ISSUE TITLE
Fullscreen is not working correctly on iOS devices

### ISSUE THREAD

**Issue by burakseyman** [brunob/leaflet.fullscreen#75]
Hello Bruno, thanks for the plugin!

I'm using the Leaflet Map plugin to show my SVG mind maps and want to give a full-screen option for the visitors.

Everything is great on desktops and Android devices. But on iOS devices, the fullscreen function is not working correctly. After clicking the button it shows the SVG mind map behind everything on the page.

Please look at the screen video: https://www.dropbox.com/s/nnx6xs4n0k63av7/RPReplay_Final1585205627.MP4?dl=0

![IMG_2101](https://user-images.githubusercontent.com/35190840/77620124-b6998980-6f4a-11ea-809b-cdfae3a26ac5.PNG)

The related web page: https://www.hukukharitalari.com/roma-hukuku-ders-notlari/roma-borclar-hukuku/

These are my codes in the full-screen.js:

L.control.fullscreen({
      position: 'topleft', // change the position of the button can be topleft, topright, bottomright or bottomleft, defaut topleft
      title: 'Tam ekran görüntüle', // change the title of the button, default Full Screen
      titleCancel: 'Tam ekrandan çık', // change the title of the button when fullscreen is on, default Exit Full Screen
       content: null, // change the content of the button, can be HTML, default null
      forceSeparateButton: false, // force seperate button to detach from zoom buttons, default false
      forcePseudoFullscreen: false, // force use of pseudo full screen even if full screen API is available, default false
      fullscreenElement: false, // Dom element to render in full screen, false by default, fallback to map._container
    }).addTo(map);

Could you please help me in this regard @brunob ?  

Thanks in advance

**Comment by HIRANO-Satoshi** [comment]
If forcePseudoFullscreen: true,  the same problem occurs on iOS Safari.
z-index seems is not working. Other elements with lower z-index or no z-index are shown up front of the map. transform/filter/perspective do not exist on parent elements.

If forcePseudoFullscreen: false,  full screen works with a large X button shown by iOS. But after returning to the normal mode, the fullscreen button disappears. This is my headache.

I'm using openstreetmap.

**Comment by brunob** [comment]
Think we can close this one since fullscreen API is not available with safari on ios device ref https://github.com/sindresorhus/screenfull.js#support

Anyway, could you test with your device on this test branch https://github.com/brunob/leaflet.fullscreen/tree/screenfull ?

**Comment by brunob** [comment]
no feedback, closing, feel free to comment if needed
