### ISSUE TITLE
How to trigger the function while Full screen on and off method in functional components

### ISSUE THREAD

**Issue by sditcshj** [brunob/leaflet.fullscreen#83]
Hi,

I am using React Leaflet. In addition, I am using the Leaflet Full-screen plugin for the Map full view option.

`<FullscreenControl  position="topright"  title="Full Screen" />`

I want to call one backend service while opening the full-screen method. How to add the event to the following method.

if anyone has an idea please share that.

**Comment by brunob** [comment]
Can't you play with enterFullscreen & exitFullscreen events ?

Please, don't charge the issue board with questions about using this script with react leaflet or other leaflet subprojects, there should be a proper place for that :)
