### ISSUE TITLE
Add to NPM to use with npm install

### ISSUE THREAD

**Issue by pouriamoosavi** [brunob/leaflet.fullscreen#84]
Hi and thanks for brilliant plugin.
Would you please consider adding a NPM package so we can use `npm install` to install this library?
Thanks

**Comment by brunob** [comment]
huhu :p

**Comment by capoaira** [comment]
Hey :)
I would like to see this plugin on NPM as well. Would it be possible to publish it there?

**Comment by brunob** [comment]
You seem to have not look at the right place... https://www.npmjs.com/package/leaflet.fullscreen

**Comment by capoaira** [comment]
Oh, I have missed that. Thank you!
