### ISSUE TITLE
FullScreen icon is not showing

### ISSUE THREAD

**Issue by sarweshkumar47** [brunob/leaflet.fullscreen#91]
Thanks for the great plugin. I've integrated this plugin into my angular project and it is working well. However, the icon is not showing on the map (just an empty box).

I tried to override the CSS and add the background image from the assets folder but no use.

    .fullscreen-icon {
        background-image: url(../../../assets/favicon.png);
    }

Any idea on how to fix this?

**Comment by brunob** [comment]
Sorry but i can't see how i could help you on this since i can't access to a demo of the bug in *your* environment.

**Comment by sarweshkumar47** [comment]
Ahh okay. I'll create a new work environment and test this plugin.

**Comment by brunob** [comment]
Any news about this one ? Is the bug still present on your side ? Can we close this issue ?

**Comment by brunob** [comment]
No feedback, closing, feel free to comment if needed.

**Comment by eoinof** [comment]
This may happen because cdnjs not longer includes images in the most recent few versions of leaflet.fullscreen
cf https://cdnjs.com/libraries/leaflet.fullscreen/2.4.0

If you load the css from there, then image will try to load from cdnjs too
