### ISSUE TITLE
Not working on Safari 14

### ISSUE THREAD

**Issue by MarioAda** [brunob/leaflet.fullscreen#92]
I've tested screenfull.js on Safari 14, and it works fine on: https://sindresorhus.com/screenfull.js/
However, Control.Fullscreen.js doesn't work

**Comment by brunob** [comment]
Tested https://brunob.github.io/leaflet.fullscreen/ with Safari 14.1.2  on Max OS 10.14.6 and it works.

Do you have any error in the console ?

**Comment by MarioAda** [comment]
@brunob After debugging Control.Fullscreen.js, the event was firing twice on the latest Safari, and so as soon as it enters fullscreen, it exits. To fix it, I had to set tap = false on the Leaflet map. Try it out on the latest Safari, not 14.1.2, and you'll see for yourself.

**Comment by brunob** [comment]
@MarioAda any news about this ?

**Comment by MarioAda** [comment]
@brunob, sorry I haven't tried it yet, but you might be right. I'll be looking into it this week

**Comment by brunob** [comment]
No feedback, closing, feel free to comment if needed.
