### ISSUE TITLE
  TypeError: Cannot read property 'fullscreenchange' of undefined

### ISSUE THREAD

**Issue by SpawnAtis** [brunob/leaflet.fullscreen#96]
Hi .When I upgraded from v1.6.0 to 2.0.0 I got this error. It is reproducible only in Jest unit tests 
`  TypeError: Cannot read property 'fullscreenchange' of undefined`

**Comment by brunob** [comment]
So you can't reproduce it in an example file ? If this happen only in a specific test environment, i can't help you without more information.

**Comment by brunob** [comment]
No feedback, closing, feel free to comment if needed.

**Comment by AMarquis1** [comment]
@SpawnAtis I'm having the same issue, how did you fix it?
